export const SET_NEXT_QUESTION = 'SET_NEXT_QUESTION';
export const SET_ANSWER_STATE = 'SET_ANSWER_STATE';
export const SET_IS_FINISHED = 'SET_IS_FINISHED';
export const RESET_STATE = 'RESET_STATE';
export const SET_QUIZES = 'SET_QUIZES';