// quiz
export const SET_NEXT_QUESTION = 'SET_NEXT_QUESTION';
export const SET_ANSWER_STATE = 'SET_ANSWER_STATE';
export const SET_IS_FINISHED = 'SET_IS_FINISHED';
export const RESET_STATE = 'RESET_STATE';
export const SET_QUIZES = 'SET_QUIZES';
export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';

// create
export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION';

// auth
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
